# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F7E4D4
background         #282C2A
cursor             #A9ACA0

active_tab_foreground     #282C2A
active_tab_background     #F7E4D4
inactive_tab_foreground   #F7E4D4
inactive_tab_background   #282C2A

active_border_color   #F7E4D4
inactive_border_color #282C2A
bell_border_color     #1D312C

color0      #4D514F
color1		#1D312C
color2		#445751
color3		#3E595E
color4		#658698
color5		#6B8DA0
color6		#AF8663
color7		#ECD1B9
color8		#A59282
color9		#27423B
color10		#5B746C
color11		#53767D
color12		#87B3CA
color13		#8EBCD5
color14		#E9B384
color15		#ECD1B9
